#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("RentACar.UI.Resource", IsApplication=true)]

namespace RentACar.UI
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060003
			public const int strArrDamageType = 2131099651;
			
			// aapt resource value: 0x7f060000
			public const int strArrFuelLevel = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int strArrRegNo = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int strArrVehicleType = 2131099649;
			
			// aapt resource value: 0x7f060005
			public const int strCleanedBy = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int strEnteredBy = 2131099654;
			
			// aapt resource value: 0x7f060004
			public const int strInspectionConditions = 2131099652;
			
			// aapt resource value: 0x7f060007
			public const int strVehicle = 2131099655;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int my_blue = 2130968576;
			
			// aapt resource value: 0x7f040004
			public const int my_gray = 2130968580;
			
			// aapt resource value: 0x7f040001
			public const int my_green = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int my_purple = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int my_red = 2130968579;
			
			// aapt resource value: 0x7f040005
			public const int splash_background = 2130968581;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int AutoSync = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int car_in = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int car_out = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int car_repair = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int CarExterior = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Download_Job = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_action_account_circle = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_action_arrow_back = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_action_arrow_forward = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_action_cancel = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_action_content_create = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ic_action_content_redo = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ic_action_content_save = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int ic_action_content_undo = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int ic_action_dashboard = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int ic_action_delete = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int ic_action_done = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int ic_action_email = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int ic_action_image = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int ic_action_photo_camera = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int ic_action_save = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int ic_action_sms = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int ic_action_social_share = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int ic_action_videocam = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int ic_launcher = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int Icon = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int LutonVan = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int rounded_corner_black = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int rounded_corner_green = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int rounded_corner_red = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int Search = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int splash_image = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int splash_screen = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int StandardVan = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int UK1 = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int UK2 = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int UK3 = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int UK4 = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int UK5 = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int UK6 = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int vehicle_in = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int vehicle_out = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int vehicle_repair = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int VehicleInteriorImg = 2130837547;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090002
			public const int DataGrid = 2131296258;
			
			// aapt resource value: 0x7f09002d
			public const int action_toolbar = 2131296301;
			
			// aapt resource value: 0x7f09000a
			public const int btnLogin = 2131296266;
			
			// aapt resource value: 0x7f090001
			public const int btnSearch = 2131296257;
			
			// aapt resource value: 0x7f090010
			public const int btnSelectImage = 2131296272;
			
			// aapt resource value: 0x7f09000c
			public const int btnStartCover = 2131296268;
			
			// aapt resource value: 0x7f09000d
			public const int btnStopCover = 2131296269;
			
			// aapt resource value: 0x7f09000f
			public const int btnTakeImage = 2131296271;
			
			// aapt resource value: 0x7f090024
			public const int chkAlloyWheel = 2131296292;
			
			// aapt resource value: 0x7f090041
			public const int chkAutoSync = 2131296321;
			
			// aapt resource value: 0x7f090017
			public const int chkBonet = 2131296279;
			
			// aapt resource value: 0x7f090025
			public const int chkBrakeFluid = 2131296293;
			
			// aapt resource value: 0x7f090023
			public const int chkCoolant = 2131296291;
			
			// aapt resource value: 0x7f09001c
			public const int chkDisc = 2131296284;
			
			// aapt resource value: 0x7f090018
			public const int chkEngine = 2131296280;
			
			// aapt resource value: 0x7f090026
			public const int chkFrontBumper = 2131296294;
			
			// aapt resource value: 0x7f090014
			public const int chkInterior = 2131296276;
			
			// aapt resource value: 0x7f090028
			public const int chkNSDoor = 2131296296;
			
			// aapt resource value: 0x7f090027
			public const int chkNSFWheel = 2131296295;
			
			// aapt resource value: 0x7f090020
			public const int chkNSRWheel = 2131296288;
			
			// aapt resource value: 0x7f09001a
			public const int chkOSDoor = 2131296282;
			
			// aapt resource value: 0x7f09001b
			public const int chkOSFWheel = 2131296283;
			
			// aapt resource value: 0x7f09001e
			public const int chkOSRWheel = 2131296286;
			
			// aapt resource value: 0x7f090021
			public const int chkOil = 2131296289;
			
			// aapt resource value: 0x7f090029
			public const int chkRearBumper = 2131296297;
			
			// aapt resource value: 0x7f090015
			public const int chkRoof = 2131296277;
			
			// aapt resource value: 0x7f09001d
			public const int chkSpareTyre = 2131296285;
			
			// aapt resource value: 0x7f09002a
			public const int chkTaligate = 2131296298;
			
			// aapt resource value: 0x7f090019
			public const int chkTools = 2131296281;
			
			// aapt resource value: 0x7f09001f
			public const int chkTyres = 2131296287;
			
			// aapt resource value: 0x7f090022
			public const int chkWasherFluid = 2131296290;
			
			// aapt resource value: 0x7f090016
			public const int chkWindScreen = 2131296278;
			
			// aapt resource value: 0x7f09003c
			public const int ddlEmailTemplate = 2131296316;
			
			// aapt resource value: 0x7f090038
			public const int ddlFuelLevel = 2131296312;
			
			// aapt resource value: 0x7f090035
			public const int ddlRegNo = 2131296309;
			
			// aapt resource value: 0x7f09003e
			public const int ddlSmsTemplate = 2131296318;
			
			// aapt resource value: 0x7f090036
			public const int ddlVehicleType = 2131296310;
			
			// aapt resource value: 0x7f090003
			public const int gridview = 2131296259;
			
			// aapt resource value: 0x7f090011
			public const int imgVehicle = 2131296273;
			
			// aapt resource value: 0x7f090030
			public const int layoutVehicleImages = 2131296304;
			
			// aapt resource value: 0x7f090033
			public const int lstCleanedBy = 2131296307;
			
			// aapt resource value: 0x7f09000e
			public const int lstDamageType = 2131296270;
			
			// aapt resource value: 0x7f090034
			public const int lstEnteredBy = 2131296308;
			
			// aapt resource value: 0x7f090032
			public const int lstInspection = 2131296306;
			
			// aapt resource value: 0x7f090031
			public const int markdamage = 2131296305;
			
			// aapt resource value: 0x7f090042
			public const int menu_back = 2131296322;
			
			// aapt resource value: 0x7f09004c
			public const int menu_cancel = 2131296332;
			
			// aapt resource value: 0x7f090043
			public const int menu_dashboard = 2131296323;
			
			// aapt resource value: 0x7f09004d
			public const int menu_delete = 2131296333;
			
			// aapt resource value: 0x7f09004b
			public const int menu_done = 2131296331;
			
			// aapt resource value: 0x7f09004a
			public const int menu_logout = 2131296330;
			
			// aapt resource value: 0x7f090048
			public const int menu_next = 2131296328;
			
			// aapt resource value: 0x7f090047
			public const int menu_save = 2131296327;
			
			// aapt resource value: 0x7f090045
			public const int menu_sendemail = 2131296325;
			
			// aapt resource value: 0x7f090044
			public const int menu_sendsms = 2131296324;
			
			// aapt resource value: 0x7f090049
			public const int menu_settings = 2131296329;
			
			// aapt resource value: 0x7f090046
			public const int menu_video = 2131296326;
			
			// aapt resource value: 0x7f090012
			public const int progressBar1 = 2131296274;
			
			// aapt resource value: 0x7f09000b
			public const int progressLayout = 2131296267;
			
			// aapt resource value: 0x7f09002e
			public const int signatureCustomer = 2131296302;
			
			// aapt resource value: 0x7f09002f
			public const int signatureDriver = 2131296303;
			
			// aapt resource value: 0x7f090004
			public const int space1 = 2131296260;
			
			// aapt resource value: 0x7f090005
			public const int space2 = 2131296261;
			
			// aapt resource value: 0x7f090007
			public const int space3 = 2131296263;
			
			// aapt resource value: 0x7f090008
			public const int space4 = 2131296264;
			
			// aapt resource value: 0x7f090013
			public const int textView1 = 2131296275;
			
			// aapt resource value: 0x7f09002b
			public const int txtDamageDetails = 2131296299;
			
			// aapt resource value: 0x7f09003a
			public const int txtEmail = 2131296314;
			
			// aapt resource value: 0x7f09003d
			public const int txtEmailTemplateContent = 2131296317;
			
			// aapt resource value: 0x7f09002c
			public const int txtLooseItems = 2131296300;
			
			// aapt resource value: 0x7f090037
			public const int txtMileage = 2131296311;
			
			// aapt resource value: 0x7f090039
			public const int txtMobile = 2131296313;
			
			// aapt resource value: 0x7f090009
			public const int txtPassword = 2131296265;
			
			// aapt resource value: 0x7f090000
			public const int txtRegNo = 2131296256;
			
			// aapt resource value: 0x7f09003b
			public const int txtSendTo = 2131296315;
			
			// aapt resource value: 0x7f090040
			public const int txtService = 2131296320;
			
			// aapt resource value: 0x7f09003f
			public const int txtSmsTemplateContent = 2131296319;
			
			// aapt resource value: 0x7f090006
			public const int txtUsername = 2131296262;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CaptureVideo = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int DownloadJob = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int list_item = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Menu = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int RentFlowCaptureDamageImage = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int RentFlowCheckList = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int RentFlowCustomerSignature = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int RentFlowDriverSignature = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int RentFlowMarkDamage = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int RentFlowSignature = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int RentFlowVehicle = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int SendEmail = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int SendSMS = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int Settings = 2130903054;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int action_menus = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int common_menu = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int dialog_complete_menu = 2131230722;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int ApplicationName = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070001
			public const int RentACarCustom_Splash = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int RentACarCustomStyleButton = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int RentACarCustomTheme = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
